// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crud.sql

package db

import (
	"context"
	"database/sql"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO account (name)
VALUES (?)
RETURNING id, name, created_at
`

func (q *Queries) CreateAccount(ctx context.Context, name string) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, name)
	var i Account
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (transaction_id, account_id, amount)
VALUES (?, ?, ?)
RETURNING id, transaction_id, account_id, amount, created_at
`

type CreateEntryParams struct {
	TransactionID int64
	AccountID     int64
	Amount        float64
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry, arg.TransactionID, arg.AccountID, arg.Amount)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (description)
VALUES (?)
RETURNING id, description, created_at
`

func (q *Queries) CreateTransaction(ctx context.Context, description sql.NullString) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction, description)
	var i Transaction
	err := row.Scan(&i.ID, &i.Description, &i.CreatedAt)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM account
WHERE id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entries
WHERE id = ?
`

func (q *Queries) DeleteEntry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntry, id)
	return err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = ?
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, created_at
FROM account
WHERE id = ?
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getAccountByName = `-- name: GetAccountByName :one
SELECT id, name, created_at
FROM account
WHERE name = ?
`

func (q *Queries) GetAccountByName(ctx context.Context, name string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByName, name)
	var i Account
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT id, transaction_id, account_id, amount, created_at
FROM entries
WHERE id = ?
`

func (q *Queries) GetEntry(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, description, created_at
FROM transactions
WHERE id = ?
`

func (q *Queries) GetTransaction(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(&i.ID, &i.Description, &i.CreatedAt)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, created_at
FROM account
ORDER BY id
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntries = `-- name: ListEntries :many
SELECT id, transaction_id, account_id, amount, created_at
FROM entries
ORDER BY id
`

func (q *Queries) ListEntries(ctx context.Context) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, description, created_at
FROM transactions
ORDER BY id
`

func (q *Queries) ListTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(&i.ID, &i.Description, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE account
SET name = ?
WHERE id = ?
RETURNING id, name, created_at
`

type UpdateAccountParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccount, arg.Name, arg.ID)
	var i Account
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE entries
SET transaction_id = ?, account_id = ?, amount = ?
WHERE id = ?
RETURNING id, transaction_id, account_id, amount, created_at
`

type UpdateEntryParams struct {
	TransactionID int64
	AccountID     int64
	Amount        float64
	ID            int64
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, updateEntry,
		arg.TransactionID,
		arg.AccountID,
		arg.Amount,
		arg.ID,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET description = ?
WHERE id = ?
RETURNING id, description, created_at
`

type UpdateTransactionParams struct {
	Description sql.NullString
	ID          int64
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, updateTransaction, arg.Description, arg.ID)
	var i Transaction
	err := row.Scan(&i.ID, &i.Description, &i.CreatedAt)
	return i, err
}
