// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Account struct {
	ID        int64
	Name      string
	CreatedAt string
}

type Entry struct {
	ID            int64
	TransactionID int64
	AccountID     int64
	Amount        float64
	CreatedAt     string
}

type Transaction struct {
	ID          int64
	Description sql.NullString
	CreatedAt   string
}
